services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=soksan
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
